[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
clap = { version = "4.5.53", features = ["derive"] }
reqwest = { version = "0.12.28", features = ["json", "blocking"] }
anyhow = "1.0"
prettytable-rs = "0.10"
serde_json = "1.0"